### ISSUE TITLE
libbeidpkcs11.so: cannot open shared object file

### ISSUE THREAD

**Issue by lsaffre** [linuxunderground/eid-mw-sdk-python#1]
Hi,
I am trying to run this example, but I am getting the following traceback:

```
$ python eid-data.py
src/dyn_unix.c:34:SYS_dyn_LoadLibrary() libbeidpkcs11.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "eid-data.py", line 48, in <module>
    beid = getData()
  File "eid-data.py", line 28, in __init__
    self.pkcs11.load('libbeidpkcs11.so')
  File "/virtualenvs/py3/lib/python3.5/site-packages/PyKCS11/__init__.py", line 482, in load
    raise PyKCS11Error(-1, pkcs11dll_filename)
PyKCS11.PyKCS11Error: Load (libbeidpkcs11.so)
```
I am working on Ubuntu 16.04 and all dependencies seem to be correctly installed. Also the file libbeidpkcs11.so.0 exists in /usr/lib/x86_64-linux-gnu/:
```
    $ sudo apt install eid-mw
    ...
    eid-mw is already the newest version (4.1.18v4.1.18-0trusty1).
    eid-mw set to manually installed.
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

    $ locate libbeidpkcs11.so
    /usr/lib/x86_64-linux-gnu/libbeidpkcs11.so.0
    /usr/lib/x86_64-linux-gnu/libbeidpkcs11.so.0.0.0

    $ cat /etc/ld.so.conf.d/x86_64-linux-gnu.conf 
    # Multiarch support
    /lib/x86_64-linux-gnu
    /usr/lib/x86_64-linux-gnu

```
Any hints about what I am missing?

**Comment by lsaffre** [comment]
Oops, after looking at the code and trying, I found a workaround: replace the line

`    self.pkcs11.load('libbeidpkcs11.so')
`
by
`    self.pkcs11.load('libbeidpkcs11.so.0')
`
Thanks for publishing this example, Vincent!
